apiVersion: v1
kind: ConfigMap
metadata:
  name: o-neko-config
data:
  application.yaml: |-
    spring:
      data:
        mongodb:
          uri: mongodb://o-neko-mongodb:27017/o-neko?
    logging:
      path: logs
    o-neko:
      security:
        credentialsCoderKey: {{- .Values.credentialsCoderKey }}
    kubernetes:
      auth:
        {{- if .Values.kubernetesAuthToken }}
        token: {{.Values.kubernetesAuthToken}}
        {{- end }}
      server:
        {{- if .Values.kubernetesUrl }}
        url: {{.Values.kubernetesUrl -}} : {{- .Values.kubernetesPort}}
        {{- end }}